# SpecPilot SDD CLI - Project Configuration
# fileID: PROJ-001
# lastUpdated: 2025-10-18
name: "SpecPilot SDD CLI"
version: "1.1.2"
language: "typescript"
framework: "node"
description: "CLI tool for initializing specification-driven development projects"
author: "Girish R"
license: "MIT"

rules:
  - "Follow specification-driven development principles"
  - "Maintain developer freedom and control"
  - "Use AI assistance for productivity, not automation"
  - "Keep documentation current and relevant"
  - "Focus on production-ready code quality"
  - "MANDATE: Update .specs/ folder files with every development milestone and code change"
  - "MANDATE: Maintain .specs/ as single source of truth for all project specifications"
  - "MANDATE: Review and update relevant .specs/ files before each commit"
  - "MANDATE: Document decisions, lessons learned, and context in .specs/context.md"
  - "MANDATE: Update .specs/prompts.md with ALL AI interactions and development prompts by default"
  - "MANDATE: Maintain chronological prompt history for complete development traceability"
  - "MANDATE: Keep file metadata and footer sections current (dates, counts, status summaries)"
  - "MANDATE: Never commit code to git unless prompted by the developer. Always ask the developer"
  - "MANDATE: Never push to git unless prompted by the developer. Always ask the developer"
  - "MANDATE: Never publish to npm unless prompted by the developer. Always ask the developer"
  -

ai-context:
  - "Assist with specification writing and validation"
  - "Provide architectural guidance without dictating decisions"
  - "Help with code quality and best practices"
  - "Track development progress and decisions"
  - "Maintain context across development sessions"
  - "MANDATE: Automatically log all prompts and responses to .specs/prompts.md"
  - "MANDATE: Include timestamps and context for all AI interactions"
